### ISSUE TITLE
Nothing appearing on map or minimap for Midsummer

### ISSUE THREAD

**Issue by Tannq** [EthanCentaurai/HandyNotes_SummerFestival#1]
I can't see anything on the maps yet there is no error message and the addon + plugin is loaded.

**Comment by Drudatz** [comment]
Yep the same Handy and Midsummer is loaded without errors, yet nothing on the map!

In case you wanna add the 2017 ones:
Dreanor:
/way Frostfire Ridge 72.58 65.02 Frostfire Ridge
/way Gorgrond 43.9 93.7 Gorgrond
/way Nagrand:Draenor 80.49 47.76 Nagrand
/way Talador 43.43 71.79 Talador
/way Spires of Arak 47.98, 44.66 Spires of Arak
/way Shadowmoon Valley:Draenor 42, 35

Broken Shore:
/way Azsuna 48.25, 29.70
/way Highmountain: Broken Isles 55.50, 84.45
/way Val'Sharah 44.88, 57.93
/way Stormheim 32.51, 42.14
/way Suramar 30.40, 45.40 Horde
/way Suramar 22.85, 58.30 Scum

**Comment by Kherae** [comment]
this is due to a change in how blizz references textures. fix is to  edit @ about line 283 in core.lua
 `if texture == "Midsummer_Thing"`  needs to be changed to `if texture == 235474`

**Comment by EthanCentaurai** [comment]
Everything should be working now. Thank you everyone for your help. :D
