### ISSUE TITLE
Control-RightClick with TomTom fails

### ISSUE THREAD

**Issue by Hemario** [EthanCentaurai/HandyNotes_SummerFestival#10]
Issue occurs for the "old" Teldrassil zone with uiMapID=57.

in TomTom.lua:858
`local zoneName = hbd:GetLocalizedMap(m)` for m=57 returns nil and this results in the following error in game.
```
4x TomTom\TomTom-v80105-1.0.0.lua:894: bad argument #5 to 'format' (string expected, got nil)
[C]: in function `format'
TomTom\TomTom-v80105-1.0.0.lua:894: in function `AddWaypoint'
HandyNotes_SummerFestival\Core.lua:126: in function <HandyNotes_SummerFestival\Core.lua:122>
HandyNotes_SummerFestival\Core.lua:138: in function <HandyNotes_SummerFestival\Core.lua:129>
HandyNotes_SummerFestival\Core.lua:149: in function <HandyNotes_SummerFestival\Core.lua:146>
[C]: ?
HandyNotes\HandyNotes-v1.5.5.lua:54: in function <HandyNotes\HandyNotes.lua:49>
HandyNotes\HandyNotes-v1.5.5.lua:172: in function `OnClick'
HandyNotes\HandyNotes-v1.5.5.lua:391: in function `OnMouseUp'
...aceBlizzard_MapCanvas\Blizzard_MapCanvas.lua:119: in function <...aceBlizzard_MapCanvas\Blizzard_MapCanvas.lua:118>
```

**Comment by EthanCentaurai** [comment]
This is an issue in HandyNotes itself I'm afraid, more specifically the HereBeDragons-2.0 library doesn't recognise Teldrassil as a zone any more. Every HandyNotes addon is affected by this, even HandyNotes itself is affected as you can't even place your own note markers there when the `/hnnew` command. This is also the reason why the bonfires in Darnassus and Dolanaar won't show on the continent map.
