### ISSUE TITLE
Module not loading at all

### ISSUE THREAD

**Issue by ChaoticWonder** [EthanCentaurai/HandyNotes_SummerFestival#3]
Got the latest from Curse including the texture fix.  Module does not load into HandyNotes.  Other modules are loading fine (Suramar_Locations, etc.).  It's like it doesn't recognize the festival is active.  Since it never loads there are no errors to report.  I am using the latest Carbonite and tried with it disabled but there was no difference.  Other modules are displaying fine with Carbonite enabled. HandyNotes reference to Carbonite issue with 1.4.x is out-dated, Carbonite fixed it long ago.

**Comment by EthanCentaurai** [comment]
There is a compatability issue between this add-on and Fishing Buddy as it is overwriting a core function necessary for this add-on to work.  If you have Fishing Buddy installed, try disabling it.  I have already contacted the author of Fishing Buddy and hope to receive a response soon.  Other than that, all I can suggest at this stage is to ensure the  HandyNotes core and SummerFestival are both up-to-date.
________________________________

**Comment by ChaoticWonder** [comment]
Disabling Fishing Buddy did the trick.  Strange it would interfere with only this one (that I know of).  Maybe something to do with detecting the Stranglethorn Tournament.

**Comment by EthanCentaurai** [comment]
That's what I'm thinking too. I have made contact with the author of Fishing Buddy with the hopes of resolving the conflict. It is highly likely that my Hallow's End and Lunar Festival plugins are affected as well. Hopefully the issue will be resolved soon. :)
