### ISSUE TITLE
HandyNotes_SummerFestival\Core.lua:57: attempt to index local 'point' (a nil value)

### ISSUE THREAD

**Issue by Thrumbar** [EthanCentaurai/HandyNotes_SummerFestival#5]
2x HandyNotes_SummerFestival\Core.lua:57: attempt to index local 'point' (a nil value)
HandyNotes_SummerFestival\Core.lua:57: in function <HandyNotes_SummerFestival\Core.lua:49>
HandyNotes_SummerFestival\Core.lua:78: in function `OnEnter'
Carbonite.Notes\NxFav.lua:1544: in function `HandyNotes'
Carbonite.Notes\NxFav.lua:1503: in function `UpdateIcons'
Carbonite\NxMap.lua:4845: in function `Update'
Carbonite\NxMap.lua:3812: in function <Carbonite\NxMap.lua:3696>

Locals:
mapFile = "BrokenIsles"
coord = 48282966
point = nil
(*temporary) = "BrokenIsles"
(*temporary) = nil
(*temporary) = ""
(*temporary) = "attempt to index local 'point' (a nil value)"
gsub = <function> defined =[C]:-1

**Comment by EthanCentaurai** [comment]
- What were you doing when this error occurred?
- Does it happen on login or at a certain time?
- Does the error happen with only HandyNotes and HandyNotes_SummerFestival enabled?
- Are all of your addons up-to-date with the latest versions?

**Comment by Thrumbar** [comment]
1.  I was using the Dalaran Herthstone to got to Legion Dalaran after completing WoD Fires.
2. The error appears upon porting into Legion Dalaran..
3 Yes only had Carbonite, HandyNotes and HandyNotes_SummerFestival 2 loaded when I tested it.
4  All addons are up to date according to Curse..

**Comment by Thrumbar** [comment]
This appears to be an issue between this addon and Carbonite Notes as the error does no happen with notes off..  It does not prevent the addon from working onoly throw the error when you first zone into Dalaran for the first time while you have not done any fires in Legion...  Once there you no longer get said error..
