### ISSUE TITLE
bug: waypoints for already completed fires

### ISSUE THREAD

**Issue by R-Adrian** [EthanCentaurai/HandyNotes_SummerFestival#6]
i have the checkbox for "Show completed" disabled but when using control+right click to define TomTom waypoints the addon is generating waypoints for the already completed fires too.

please do not generate such waypoints if that checkbox is not enabled.

**Comment by Aditza2015** [comment]
(note: currently using Version: v1.4.1 from curse)

**Comment by Aditza2015** [comment]
oh well... event is now over,

**Comment by R-Adrian** [comment]
1 year later... *bump*
Blizzard's event is now active again... any chance of fixing this?

**Comment by R-Adrian** [comment]
THANK YOU :)
