### ISSUE TITLE
Not showing map locations 2019

### ISSUE THREAD

**Issue by ArchmageValexion** [EthanCentaurai/HandyNotes_SummerFestival#8]
Midsummer has started, and I've loaded all the most recent HandyNotes and the SummerFestival addons, but the locations aren't appearing on the map at all. I've tried reinstalling both addons, reloading the game, and even relaunching the game. I've tried multiple characters, disabling and enabling the addon in-game, and toggling completed bonfires just in case it was flagging them as completed.

**Comment by EthanCentaurai** [comment]
There's been some weirdness in the Calendar API the addon uses to check to see if the world event is active. Are you using the v1.6 release or the v1.6-3 alpha? Please use the [alpha from WoWace](https://www.wowace.com/projects/handynotes_summerfestival/files/2728222) if you can as the workaround I added *might* have solved it.

**Comment by Azulia** [comment]
Have tried all three versions, including logging out, re download, it just won't work

**Comment by EthanCentaurai** [comment]
Is it printing anything in the chatbox?

**Comment by Azulia** [comment]
Heya, it is currently working, I had to reload the ui, have to that each
time I log in tho. Ty for the fast reply

Op ma 24 jun. 2019 18:13 schreef Ethan Centaurai <notifications@github.com>:

**Comment by EthanCentaurai** [comment]
It's a bit temperamental in the v1.6 release on CurseForge and I don't understand why (i.e., it works for me but not everyone). I've made some changes in the v1.6.1 beta on CurseForge to hopefully make it more reliable and so far the response has been positive.

**Comment by Azulia** [comment]
Well as long as I get it to work by reloading my ui I am happy. Ty for the
time you put in this🙂

Op ma 24 jun. 2019 18:30 schreef Ethan Centaurai <notifications@github.com>:

**Comment by EthanCentaurai** [comment]
I haven't heard anything more about this issue so I'm going to assume the fix worked and will close this issue for now. If the problem comes back, please reopen this issue.
